<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>Nonogram_WF</RootNamespace>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>

	  <ApplicationHighDpiMode>SystemAware</ApplicationHighDpiMode>
  </PropertyGroup>

  <ItemGroup>
    <Compile Update="Views\login.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Views\Welcome.cs">
      <SubType>UserControl</SubType>
    </Compile>
  </ItemGroup>

</Project>